version: '2.1'
volumes:
  settings:
  # spotifycache:
  # snapcast:
services:
  magicmirror:
    restart: always
    build: ./magicmirror
    privileged: true
    network_mode: host
    environment:
      TZ: EST+5EDT,M3.2.0/2,M11.1.0/2
      TIMEZONE: America/New_York

  kiosk:
    restart: always
    build: ./balena-dash/kiosk
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'settings:/usr/src/app/settings'
    environment:
      LAUNCH_URL: http://192.168.1.19:90
      TIMEZONE: America/New_York

  # wifi-connect:
  #   build: ./balena-dash/wifi-connect
  #   restart: always
  #   network_mode: host
  #   privileged: true
  #   ports:
  #     - "8181:8181"
  #   labels:
  #     io.balena.features.dbus: '1'
  #     io.balena.features.firmware: '1'
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  # # Core services
  # audio:
  #   build: ./balena-sound/core/audio
  #   privileged: true
  #   labels:
  #     io.balena.features.dbus: 1
  #   ports:
  #     - 4317:4317
  #   volumes:
  #     - snapcast:/var/cache/snapcast

  # sound-supervisor:
  #   build: ./balena-sound/core/sound-supervisor
  #   network_mode: host
  #   ports:
  #     - 3000:3000
  #   labels:
  #     io.balena.features.supervisor-api: 1

  # multiroom-server:
  #   build: ./balena-sound/core/multiroom/server
  #   restart: on-failure
  #   ports:
  #     - 1704:1704
  #     - 1705:1705
  #     - 1780:1780
  #   volumes:
  #     - snapcast:/var/cache/snapcast

  # multiroom-client:
  #   build: ./balena-sound/core/multiroom/client
  #   restart: on-failure

  # spotify:
  #   build: ./balena-sound/plugins/spotify
  #   restart: on-failure
  #   privileged: true
  #   network_mode: host
  #   volumes:
  #     - spotifycache:/var/cache/raspotify
