version: '2.1'
volumes:
  mm-data:
  spotifycache:
  snapcast:
services:
  magicmirror:
    restart: always
    build: ./magicmirror
    privileged: true
    network_mode: host
    volumes:
      - 'mm-data:/usr/src/data'
    environment:
      TZ: America/New_York
      TIMEZONE: America/New_York

  kiosk:
    image: balenablocks/browser:raspberrypi4-64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    environment:
      KIOSK: 1
      LAUNCH_URL: http://localhost:90
      ROTATE_DISPLAY: right
      TZ: America/New_York
      TIMEZONE: America/New_York

  # # # Core services
  audio:
    build: ./balena-sound/core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317
    volumes:
      - snapcast:/var/cache/snapcast
    environment:
      AUDIO_OUTPUT: RPI_HDMI0
      SOUND_VOLUME: 100
      SOUND_MODE: STANDALONE
      SOUND_DEVICE_NAME: mirror
      BLUETOOTH_DEVICE_NAME: mirror

  sound-supervisor:
    build: ./balena-sound/core/sound-supervisor
    network_mode: host
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      AUDIO_OUTPUT: RPI_HDMI0
      SOUND_VOLUME: 100
      SOUND_MODE: STANDALONE
      SOUND_DEVICE_NAME: mirror
      BLUETOOTH_DEVICE_NAME: mirror

  multiroom-server:
    build: ./balena-sound/core/multiroom/server
    restart: on-failure
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - snapcast:/var/cache/snapcast
    environment:
      AUDIO_OUTPUT: RPI_HDMI0
      SOUND_VOLUME: 100
      SOUND_MODE: STANDALONE
      SOUND_DEVICE_NAME: mirror
      BLUETOOTH_DEVICE_NAME: mirror

  multiroom-client:
    build: ./balena-sound/core/multiroom/client
    restart: on-failure
    environment:
      AUDIO_OUTPUT: RPI_HDMI0
      SOUND_VOLUME: 100
      SOUND_MODE: STANDALONE
      SOUND_DEVICE_NAME: mirror
      BLUETOOTH_DEVICE_NAME: mirror

  spotify:
    build: ./balena-sound/plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify
    environment:
      AUDIO_OUTPUT: RPI_HDMI0
      SOUND_VOLUME: 100
      SOUND_MODE: STANDALONE
      SOUND_DEVICE_NAME: mirror
      BLUETOOTH_DEVICE_NAME: mirror

  monitorcontrol:
    build: ./pir
    restart: on-failure
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1
