version: '2'
services:
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    ports:
      - "8181:8181"
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
